FROM ubuntu
MAINTAINER Nikita V. Shirokov tehnerd@tehnerd.com
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449 && \
    add-apt-repository "deb http://dl.hhvm.com/ubuntu $(lsb_release -sc) main" && \
    apt-get update && \
    apt-get install -y hhvm
